### ISSUE TITLE
Compile error after updating to 0.12.x

### ISSUE THREAD

**Issue by williamweckl** [akira/exq_ui#116]
After updating to 0.12.0 or 0.12.1, a compilation error happens:

```
== Compilation error in file lib/exq_ui_web/live/components/table_component.ex ==
** (Phoenix.LiveView.HTMLTokenizer.ParseError) lib/exq_ui_web/live/components/table_component.html.heex:1:1: attribute "phx-hook" requires the "id" attribute to be set
    (phoenix_live_view 0.17.9) lib/phoenix_live_view/html_engine.ex:778: Phoenix.LiveView.HTMLEngine.validate_phx_attrs!/5
    (phoenix_live_view 0.17.9) lib/phoenix_live_view/html_engine.ex:428: Phoenix.LiveView.HTMLEngine.handle_token/2
    (elixir 1.13.3) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.17.9) lib/phoenix_live_view/html_engine.ex:53: Phoenix.LiveView.HTMLEngine.handle_body/1
    (phoenix_live_view 0.17.9) expanding macro: Phoenix.LiveView.Renderer.__before_compile__/1
    lib/exq_ui_web/live/components/table_component.ex:1: ExqUIWeb.TableComponent (module)
```

I've checked and there is missing the id attribute for the div that sets `phx-hook`, just like the error message inform us. Adding some id attribute the application is able to compile.
