### PR TITLE
Fix compile issue for missing id attribute.

### LINKED ISSUE #116: Compile error after updating to 0.12.x
After updating to 0.12.0 or 0.12.1, a compilation error happens:

```
== Compilation error in file lib/exq_ui_web/live/components/table_component.ex ==
** (Phoenix.LiveView.HTMLTokenizer.ParseError) lib/exq_ui_web/live/components/table_component.html.heex:1:1: attribute "phx-hook" requires the "id" attribute to be set
    (phoenix_live_view 0.17.9) lib/phoenix_live_view/html_engine.ex:778: Phoenix.LiveView.HTMLEngine.validate_phx_attrs!/5
    (phoenix_live_view 0.17.9) lib/phoenix_live_view/html_engine.ex:428: Phoenix.LiveView.HTMLEngine.handle_token/2
    (elixir 1.13.3) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.17.9) lib/phoenix_live_view/html_engine.ex:53: Phoenix.LiveView.HTMLEngine.handle_body/1
    (phoenix_live_view 0.17.9) expanding macro: Phoenix.LiveView.Renderer.__before_compile__/1
    lib/exq_ui_web/live/components/table_component.ex:1: ExqUIWeb.TableComponent (module)
```

I've checked and there is missing the id attribute for the div that sets `phx-hook`, just like the error message inform us. Adding some id attribute the application is able to compile.

### PR DESCRIPTION
**Pull request by williamweckl**
Fixes #116

### CODE REVIEW

**Comment by ananthakumaran** [comment]
Thanks, could you also update phoenix_live_view `mix deps.update phoenix_live_view`. Apparently, this check is introduced somewhere between 0.17.5 to 0.17.9.

**Comment by williamweckl** [comment]
Done! But for some reason it updated a lot more than just phoenix_live_view...

```
[01:56] william@william-pc:~/dev/exq_ui (patch-1)* $ mix deps.update phoenix_live_view
warning: use Mix.Config is deprecated. Use the Config module instead
  config/config.exs:1

warning: use Mix.Config is deprecated. Use the Config module instead
  config/dev.exs:1
  
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  cowboy 2.9.0
  cowlib 2.11.0
  earmark_parser 1.4.18
  elixir_uuid 1.2.1
  ex_doc 0.26.0
  exq 0.16.2
  file_system 0.2.10
  floki 0.31.0
  html_entities 0.5.2
  jason 1.3.0
  makeup 1.0.5
  makeup_elixir 0.15.2
  makeup_erlang 0.1.1
  mime 2.0.2
  nimble_parsec 1.2.0
  phoenix_html 3.2.0
  phoenix_live_reload 1.3.3
  plug_cowboy 2.5.2
  plug_crypto 1.2.2
  ranch 1.8.0
  redix 1.1.5
Upgraded:
  cowboy_telemetry 0.3.1 => 0.4.0 (minor)
  phoenix 1.6.6 => 1.6.7
  phoenix_live_view 0.17.5 => 0.17.9
  phoenix_pubsub 2.0.0 => 2.1.1
  phoenix_view 1.1.0 => 1.1.2
  plug 1.12.1 => 1.13.6
  telemetry 0.4.3 => 1.1.0 (major)
* Updating phoenix_live_view (Hex package)
* Updating telemetry (Hex package)
* Updating cowboy_telemetry (Hex package)
* Updating plug (Hex package)
* Updating phoenix (Hex package)
* Updating phoenix_pubsub (Hex package)
* Updating phoenix_view (Hex package)
```

**Comment by williamweckl** [comment]
@ananthakumaran could this be released?

**Comment by akira** [comment]
Hi William,

Thanks for the PR and heads up - I’ve been on vacation and haven’t gotten a
chance to release but will do it shortly. Thanks!!

**Comment by akira** [comment]
Just released 0.12.2. thanks again @williamweckl!!✨
